version: '3.8'

services:
  streamlit-app:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    environment:
      - PYTHONUNBUFFERED=1

  fastapi-app:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      - PYTHONUNBUFFERED=1
